version: '3'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474"
      - "7687"
  redis:
    image: redis:latest
    ports:
      - "6379"
  conductor:
    build: .
    ports: 
      - "8675"
    depends_on:
      - "redis"
      - "neo4j"
    environment:
      - STAGE=1
    