version: '3'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474"
      - "7687"
    environment:
      - NEO4J_AUTH=neo4j/localInsecurePassword
  redis:
    image: redis:latest
    ports:
      - "6379"
  kafka:
    image: spotify/kafka:latest
    ports: 
      - "9092"
    environment:
      - ADVERTISED_HOST=localhost
      - ADVERTISED_PORT=9092
  conductor:
    build: .
    ports: 
      - "8675"
    depends_on:
      - "redis"
      - "neo4j"
      - "kafka"
    environment:
      - STAGE=1
    